package com.schwab.agenticsdlc.agent;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Utility class for extracting raw source code from Markdown code fence blocks.
 *
 * <p>Supports multi-fence extraction to handle all file types generated by the 2-phase
 * code synthesis pipeline:
 * <ul>
 *   <li>{@code ```java} — Java source files</li>
 *   <li>{@code ```xml} — Maven {@code pom.xml}</li>
 *   <li>{@code ```yaml} / {@code ```yml} — Spring Boot {@code application.yml}</li>
 *   <li>{@code ```properties} — {@code application.properties}</li>
 *   <li>{@code ```json} — JSON config files</li>
 *   <li>{@code ```} — Plain fence fallback (catches any unrecognized language tag)</li>
 * </ul>
 *
 * <p>Fence types are tried in priority order. The first matching fence wins.
 */
public class MarkdownCodeExtractor {

    private static final Logger logger = LoggerFactory.getLogger(MarkdownCodeExtractor.class);

    /**
     * Ordered list of supported Markdown fence types.
     * Tried in sequence — the first matching fence is extracted.
     */
    private static final String[] FENCE_PRIORITY = {
            "```java",
            "```xml",
            "```yaml",
            "```yml",
            "```json",
            "```properties",
            "```"  // generic fallback — catches any unrecognized language tag
    };

    /**
     * Extracts the raw source code from a Markdown code fence block.
     *
     * <p>Tries each supported fence type in priority order. For each candidate fence,
     * code is extracted from the character after the opening newline to the closing {@code ```}.
     *
     * @param markdownContent The LLM response containing a Markdown code block.
     * @return The extracted raw source code, trimmed of leading/trailing whitespace.
     * @throws IllegalArgumentException if no recognizable code block is found.
     */
    public static String extractCode(String markdownContent) {
        if (markdownContent == null || markdownContent.isBlank()) {
            throw new IllegalArgumentException("Markdown content cannot be null or blank.");
        }

        for (String fence : FENCE_PRIORITY) {
            int fenceStart = markdownContent.indexOf(fence);
            if (fenceStart == -1) continue;

            // Move past the fence token to find the newline that ends the opening fence line
            int newlineAfterFence = markdownContent.indexOf('\n', fenceStart);
            if (newlineAfterFence == -1) continue;

            int codeStart = newlineAfterFence + 1;  // first char of actual code
            int closingFence = markdownContent.indexOf("```", codeStart);
            if (closingFence == -1) continue;

            String extracted = markdownContent.substring(codeStart, closingFence).trim();
            if (!extracted.isBlank()) {
                logger.debug("[MarkdownCodeExtractor]: Extracted {} chars using fence '{}'.",
                        extracted.length(), fence);
                return extracted;
            }
        }

        throw new IllegalArgumentException(
                "No recognizable code block found in the provided Markdown content. " +
                "Supported fences: java, xml, yaml, yml, json, properties, or plain ```.");
    }
}
